<?php
/**
 * @var $block Magento\Framework\View\Element\Template
 * @var $_helper Spirit\BestpriceAnalytics\ViewModel\Config
 */
$_helper = $block->getData('config');
?>
<!-- BESTPRICE ANALYTICS CODE start -->
<script>
    (function (a, b, c, d, s) {a.__bp360 = c;a[c] = a[c] || function (){(a[c].q = a[c].q || []).push(arguments);};
        s = b.createElement('script'); s.async = true; s.src = d; s.charset = 'utf-8'; (b.body || b.head).appendChild(s);})
    (window, document, 'bp', '//360.bestprice.gr/360.js');

    bp('connect', '<?= /* @noEscape */ $_helper->get360Key(); ?>');
</script>
<!-- BESTPRICE ANALYTICS CODE end -->
<?php if ($_helper->getBadgeActive()): ?>
    <script src="https://scripts.bestprice.gr/badge.js" async="true" data-float="<?php echo $_helper->getBadgePosition()?>"></script><noscript><a href="https://www.bestprice.gr">BestPrice.gr</a></noscript>
<?php endif; ?>
